### ISSUE TITLE
Microsoft.Extensions.Logging support

### ISSUE THREAD

**Issue by lp-brainspire** [filipw/dotnet-script#533] opened 2020-04-20 19:04 UTC
We'd like to leverage an internal logging dll and having issues `using` it from a .csx script.

Here's what the script looks like:

```csharp
//#r "nuget: Microsoft.Extensions.Logging, 3.1.2"
//#r "nuget: Microsoft.Extensions.Logging.Console, 3.1.2"
//#r "nuget: Microsoft.Extensions.Logging.Abstractions, 3.1.2"

#r "..\Company.Logging\bin\Debug\netcoreapp3.1\Company.Logging.dll"

//using Microsoft.Extensions.Logging;
using Company.Logging;
Company.Logging.Logger.LogInformation("Test Begin");
```

We've tried with and without the commented lines, above.  Either way we get the same error:

```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. Could not find or load a specific file. (0x80131621)
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   at System.Runtime.Loader.AssemblyLoadContext.OnAssemblyResolve(RuntimeAssembly assembly, String assemblyFullName)
   at Company.Logging.Logger.LogInformation(String info, Object[] args)
   at Submission#0.<<Initialize>>d__0.MoveNext() in C:\user\Company\Company.Scripts\TestIndirectLogging.csx:line 9
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in D:\a\1\s\src\Dotnet.Script.Core\ScriptRunner.cs:line
53
```

Here's the [repo](https://github.com/lp-brainspire/DotnetScriptMicrosoftLogging) containing the stripped down dependency project and script.

We're working with `netcoreapp3.1` (`3.1.2 runtime` and `3.1.102+ sdk`).  We've tried both `windows 10 pro` and `ubuntu linux 18.04` and receive the same error.

The following may be two separate issues, but the above repo also contains these test scripts:

* [TestDirectLogging.csx](https://github.com/lp-brainspire/DotnetScriptMicrosoftLogging/blob/master/Company.Scripts/TestDirectLogging.csx) - Does bare minimum Microsoft.Extensions.Logging without a dependency project.  Outputs just fine on linux with `--verbosity d`.  However, the expected output is not there for windows.

* [TestDirectLoggingDebug.csx](https://github.com/lp-brainspire/DotnetScriptMicrosoftLogging/blob/master/Company.Scripts/TestDirectLoggingDebug.csx) - Tries to pull in debug logging with `builder.AddDebug();`, but yields dependency conflicts with its parent `Microsoft.Extensions.Logging`.  See the error message at that link.

It seems like Microsoft.Extensions.Logging doesn't want to get along one way or another with our dotnet scripts.  We'll try to press forward with Console.WriteLine and see how far we can get, but would appreciate an help with these issues or concerning the best way to set up logging for our scripts, or any success others have had getting it to work.

Exciting project, thanks for all your work!

**Comment by filipw** [comment] 2020-04-21 08:59
thank you - this should already be fixed on master, we will release it today.
There is often a problem, unfortunately, with the assemblies referenced by both the dotnet-script itself (like Newtonsoft.Json or Microsoft.Extensions.Logging) and the script itself, which is the root cause here.

**Comment by lp-brainspire** [comment] 2020-04-22 14:20
Thanks - it works now with [0.52.0](https://github.com/filipw/dotnet-script/releases/tag/0.52.0)!  The exception is gone and `builder.AddDebug()` works to get stdout working in windows now.

For my education, was this already an issue that I missed, or documented somewhere that I might read up on?

I'll let you close when you're ready, in case you're still tracking this.

**Comment by seesharper** [comment] 2020-04-22 21:37
I think it just boils down to a version mismatch for Microsoft.Extensions.Logging between what you had in your script and what dotnet-script used internally. We have now bumped this dependency to the latest version (3.1.3).

**Closed** 2020-04-22 21:37 UTC
Labels: bug
