### ISSUE TITLE
nuget references not recognized when using Visual Studio Code

### ISSUE THREAD

**Issue by ChiefInnovator** [filipw/dotnet-script#531] opened 2020-04-13 03:49 UTC
I have the following script.  It works fine from the command line, but errors when using Visual Studio Code.  I suspect that this might be an OmniSharp issue, but I haven't found a workaround.

// This is a comment
#r "nuget: Pineapple"

using static Pineapple.Common.Preconditions;

try
{
    object client = null;
    CheckIsNotNull(nameof(client), client);
}
catch (Exception ex)
{
    Console.WriteLine(ex.Message);
}

Console.WriteLine($@"Rich Was Here! {DateTime.Now.ToLongTimeString()}");

**Comment by filipw** [comment] 2020-04-21 09:01
could you post your OminSharp log?

**Comment by ChiefInnovator** [comment] 2020-05-19 10:47
Sorry been busy with COVID-19 work issues.  Will see if I can reproduce the issue.

**Comment by realivanjx** [comment] 2020-06-19 13:52
Here is my case with mongodb driver:

![image](https://user-images.githubusercontent.com/12814796/85139562-cdf8c200-b26e-11ea-866e-cdd38242917c.png)


```
Starting OmniSharp server at 6/19/2020, 20:49:17
    Target: c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts

OmniSharp server started.
    Path: c:\Users\Ivan\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\OmniSharp.exe
    PID: 19896

[info]: OmniSharp.Stdio.Host
        Starting OmniSharp on Windows 6.2.9200.0 (x64)
[info]: OmniSharp.Services.DotNetCliService
        DotNetPath set to dotnet
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Located 2 MSBuild instance(s)
            1: Visual Studio Community 2019 16.6.30114.105 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
            2: StandAlone 16.4 - "c:\Users\Ivan\.vscode\extensions\ms-dotnettools.csharp-1.22.1\.omnisharp\1.35.3\.msbuild\Current\Bin"
[info]: OmniSharp.MSBuild.Discovery.MSBuildLocator
        Registered MSBuild instance: Visual Studio Community 2019 16.6.30114.105 - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin"
[info]: OmniSharp.Cake.CakeProjectSystem
        Detecting Cake files in 'c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts'.
[info]: OmniSharp.Cake.CakeProjectSystem
        Could not find any Cake files
[info]: OmniSharp.MSBuild.ProjectSystem
        No solution files found in 'c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts'
[info]: OmniSharp.Script.ScriptProjectSystem
        Detecting CSX files in 'c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts'.
[info]: OmniSharp.Script.ScriptProjectSystem
        Found 1 CSX files.
[info]: OmniSharp.Script.ScriptContextProvider
        Searching for compilation dependencies with the fallback framework of 'net461'.
[fail]: OmniSharp.Script.ScriptContextProvider
        Failed to resolve compilation dependencies
[info]: OmniSharp.Script.ScriptContextProvider
        Unable to find dependency context for CSX files. Will default to non-context usage (Desktop CLR scripts).
[info]: OmniSharp.Script.ScriptProjectSystem
        Added CSX project 'c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts\db-clean.csx' to the workspace.
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.CSharpFormattingWorkspaceOptionsProvider, Order: 0
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.RenameWorkspaceOptionsProvider, Order: 100
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.ImplementTypeWorkspaceOptionsProvider, Order: 110
[info]: OmniSharp.WorkspaceInitializer
        Invoking Workspace Options Provider: OmniSharp.Roslyn.CSharp.Services.BlockStructureWorkspaceOptionsProvider, Order: 140
[info]: OmniSharp.WorkspaceInitializer
        Configuration finished.
[info]: OmniSharp.Stdio.Host
        Omnisharp server running using Stdio at location 'c:\Users\Ivan\Documents\projects\xtreme-unlock\xtreme-unlock.Scripts' on host 9700.

```

**Comment by filipw** [comment] 2020-06-19 14:24
The log shows `Unable to find dependency context for CSX files. Will default to non-context usage (Desktop CLR scripts).`

it means you have not activated the dotnet-script compatible mode in OmniSharp and it defaults to CSI mode. you need to add `omnisharp.json` file at the root of your workspace. you can also add it globally using these instructions https://github.com/OmniSharp/omnisharp-roslyn/wiki/Configuration-Options#global-omnisharpjson

```
{
  "script": {
    "enableScriptNuGetReferences": true,
    "defaultTargetFramework": "netcoreapp3.1"
  }
}
```

`dotnet script init` also generates the relevant `omnisharp.json`

**Comment by realivanjx** [comment] 2020-06-19 14:42
Thanks it worked now

**Comment by filipw** [comment] 2020-06-19 14:44
I will close this presuming the original problem was also caused by this. thanks

**Closed by filipw** 2020-06-19 14:44 UTC
