### ISSUE TITLE
PowerShell installation script not working

### ISSUE THREAD

**Issue by fmajestic** [filipw/dotnet-script#231] opened 2018-03-06 16:22 UTC
Copy-pasting the command gives these two errors:
```
PS C:\Users\Filip> (new-object Net.WebClient).DownloadString("https://raw.githubusercontent.com/filipw/dotnet-script/mas
ter/install/install.ps1") | iex


    Directory: C:\Users\Filip\AppData\Local\Temp


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        6.3.2018.     16:10                dotnet-script
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:6 char:18
+ ... stRelease = Invoke-WebRequest "https://api.github.com/repos/filipw/do ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

Downloading latest verson ()
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure channe
l."
At line:16 char:1
+ $client.DownloadFile($url,$zipFile)
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Microsoft.PowerShell.Archive\Expand-Archive : The path 'C:\Users\Filip\AppData\Local\Temp\dotnet-script\dotnet-script.zip' either does not exist or is not a valid file system path.
At line:19 char:1
+ Microsoft.PowerShell.Archive\Expand-Archive $zipFile -DestinationPath ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\Filip\...tnet-script.zip:String) [Expand-Archive], InvalidOperationException
    + FullyQualifiedErrorId : ArchiveCmdletPathNotFound,Expand-Archive
```

PowerShell version:
```
PS C:\Users\Filip> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  248
```

**Comment by filipw** [comment] 2018-03-06 16:38
Thanks, it was caused by Github enforcing TLS 1.2. Fixed in #232

**Closed** 2018-03-06 18:45 UTC
