### ISSUE TITLE
Issues trying to use EF with dotnet-script

### ISSUE THREAD

**Issue by Sharpiro** [filipw/dotnet-script#86] opened 2017-06-17 19:01 UTC
I've found an issue trying to run a particular script that uses entity framework with dotnet-script.  The script runs fine when executed under csi.exe.

The uncommented ```#r``` commands are necessary for this script to run under csi.exe.  The ones that are commented out are me responding to the errors i get when trying to run under dotnet-script in vs code.

When trying to get this to work i've seen various errors including:

- ```type X is not defined, must reference X.Y```
- ```not found: '!!0 Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService(System.IServiceProvider)'. ```
- ```Exception thrown: 'System.BadImageFormatException' in System.Private.CoreLib.ni.dll Cannot load a reference assembly for execution.```
- And then messages that would say IQueryable is defined in multiple assemblies

```
// these dlls are needed to use entity framework
#r "C:\Users\sharpiro\.nuget\packages\microsoft.entityframeworkcore\1.1.2\lib\net451\Microsoft.EntityFrameworkCore.dll"
#r "C:\Users\sharpiro\.nuget\packages\system.interactive.async\3.0.0\lib\net45\System.Interactive.Async.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.dependencyinjection\1.1.0\lib\netstandard1.1\Microsoft.Extensions.DependencyInjection.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.dependencyinjection.abstractions\1.1.0\lib\netstandard1.0\Microsoft.Extensions.DependencyInjection.Abstractions.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.logging.abstractions\1.1.1\lib\netstandard1.1\Microsoft.Extensions.Logging.Abstractions.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.logging\1.1.1\lib\netstandard1.1\Microsoft.Extensions.Logging.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.caching.memory\1.1.1\lib\net451\Microsoft.Extensions.Caching.Memory.dll"
#r "C:\Users\sharpiro\.nuget\packages\remotion.linq\2.1.1\lib\net45\Remotion.Linq.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.options\1.1.1\lib\netstandard1.0\Microsoft.Extensions.Options.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.caching.abstractions\1.1.1\lib\netstandard1.0\Microsoft.Extensions.Caching.Abstractions.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.entityframeworkcore\1.1.2\lib\net451\Microsoft.EntityFrameworkCore.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.entityframeworkcore.sqlserver\1.1.2\lib\net451\Microsoft.EntityFrameworkCore.SqlServer.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.entityframeworkcore.relational\1.1.2\lib\net451\Microsoft.EntityFrameworkCore.Relational.dll"
#r "C:\Users\sharpiro\.nuget\packages\system.diagnostics.diagnosticsource\4.3.1\lib\net46\System.Diagnostics.DiagnosticSource.dll"
#r "C:\Users\sharpiro\.nuget\packages\microsoft.extensions.primitives\1.1.0\lib\netstandard1.0\Microsoft.Extensions.Primitives.dll"

// trying dlls that c# interactive window uses
// #r "C:\windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll"
// #r "C:\windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll"
// #r "C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll"

// trying dlls that 4.6 uses
// #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.dll"
// #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Core.dll"
// #r "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6\System.Data.dll"

using Microsoft.EntityFrameworkCore;
public class MyContext : DbContext
{
    public DbSet<Log> Logs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("empty");
}

public class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}

var context = new MyContext();
var logsQueryable = context.Logs.Take(1);
WriteLine(logsQueryable);
```

**Comment by seesharper** [comment] 2017-06-18 20:28
Could you post your project.json file?

**Comment by Sharpiro** [comment] 2017-06-19 01:20
Bad news.  I'm actually using a pretty new setup where I only have the dotnet w/ msbuild tooling.  So i'm using a slightly modified dotnet-script that essentially comments out the portion where it reads in the project.json file, so that I could use it w/o that file.

I tried getting the old tooling installed by installing old runtimes/sdks to get a better test case for you, but i couldn't figure it out.  So I haven't setup the best test case due to that, but I think it's still an issue w/ the ```#r``` command in dotnet-script.  Sorry about that.

**Comment by filipw** [comment] 2017-06-19 06:26
This is really as expected. While `csi` and `dotnet-script` are compatible syntactically, they will not be compatible at runtime.
`csi` runs your code on desktop CLR while `dotnet-script` runs your code on CoreCLR. This means that the references you bring in with `#r` must be different for in each case. For example referencing a `net451` assembly will blow up on CoreCLR. This is why I recommend to use the package resolution that's built into `dotnet-script` rather than trying to manually import dependencies.

If you are on older `dotnet CLI` it will not prevent you from using `dotnet-script`. All you need to do is to add a `global.json` file next to your script where you force an older version of `dotnet CLI` in *that particular folder* only:

```
{
    "sdk": 
    {
        "version": "1.0.0-preview2-003156"
    }
}
```

This will - provided that you installed `1.0.0-preview2-003156` on your machine (you can have many CLI versions side by side) - allow you to use `dotnet restore` and `project.json` for references.

**Comment by Sharpiro** [comment] 2017-06-19 13:58
Thank you for the explanation, I am now able to get the project.json style dotnet core apps to restore using the global.json you posted.

However, I'm still unable to get EF working with dotnet-script.  When using VS2017 dotnet core w/ msbuild, I can simply add a reference to "Microsoft.EntityFrameworkCore.SqlServer" 1.1.2 and then all sub-dependencies are automatically retrieved and everything works fine.  But when using dotnet-script, it seems like certain sub-assemblies are unable to be loaded, such as "System.Data.Common".  I tried adding that nuget package explicitly, but still no luck.

Here is the setup:

project.json
```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.2"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  },
  "tools": {
    "Dotnet.Script": {
      "version": "0.9.0-beta",
      "imports": [
        "portable-net45+win8",
        "dnxcore50"
      ]
    }
  }
}
```

Main.csx
```
using Microsoft.EntityFrameworkCore;
using System.Linq;

public class MyContext : DbContext
{
    public DbSet<Log> Logs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("empty");
}

public class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}

var context = new MyContext();
try
{
    var logsQueryable = context.Logs.Take(1);
    Console.WriteLine(logsQueryable);
}
catch (Exception ex)
{
    Console.WriteLine("An error occurred!");
    Console.WriteLine(ex);
}
```

Exception:
```
An error occurred!
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The sy
stem cannot find the file specified.
File name: 'System.Data.Common, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the spec
ified file.
File name: 'System.Data.Common'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.Extensions.DependencyInjection.SqlServerServiceCollectionExtensions.AddEntityFrameworkSqlServer(IServiceCollection services)
   at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c__DisplayClass4_1.<GetOrAdd>b__2(Int64 k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.DbContext.InitializeServices()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.DbContext.get_QueryProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.<.ctor>b__3_0()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Take[TSource](IQueryable`1 source, Int32 count)
   at Submission#0.<<Initialize>>d__0.MoveNext()
```

Expected output (works in VS 2017 w/ msbuild dotnet core):
```
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[ScaffoldingCore.Log]
```

Notes:

- I tried with both "Dotnet.Script": "0.9.0-beta" and "Dotnet.Script": "0.7.0-beta" packages
- I tried adding System.Data.Common package to my project.json but to no avail

**Comment by seesharper** [comment] 2017-06-20 07:23
try adding System.Data.Common, 4.1.0 to your project.json file

**Comment by Sharpiro** [comment] 2017-06-20 17:35
@seesharper that actually did work and caused my above example to work.  However now I'm getting errors related to SqlClient when i adjust the example to try and get data.

Script:
```
using Microsoft.EntityFrameworkCore;
using System.Linq;

public class MyContext : DbContext
{
    public DbSet<Log> Logs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("empty");
}

public class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}

var context = new MyContext();
try
{
    var logsQueryable = context.Logs.ToList();
    Console.WriteLine(logsQueryable);
}
catch (Exception ex)
{
    Console.WriteLine("An error occurred!");
    Console.WriteLine(ex);
}
```

project.json:
```
{
  "dependencies": {
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.2",
    "System.Data.Common": "4.1.0",
    "System.Data.SqlClient": "4.1.0"
  },
  "frameworks": {
    "netcoreapp1.0": {}
  },
  "tools": {
    "Dotnet.Script": {
      "version": "0.9.0-beta",
      "imports": [
        "portable-net45+win8",
        "dnxcore50"
      ]
    }
  }
}
```

Exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, P
ublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNot
FoundException: Could not load the specified file.
File name: 'System.Data.SqlClient'
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyNam
e assemblyName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTransientExceptionDetector.ShouldRetryOn(Exception ex)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Fu
nc`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionIntercepto
r.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Submission#0.<<Initialize>>d__0.MoveNext()
```

You can see I'm adding ```"System.Data.SqlClient": "4.1.0"```, but it's making no difference.

I also noticed that a simple line trying to consume a class in the SqlClient assembly will fail, when using the same project.json as above.
```
var clientType = typeof(System.Data.SqlClient.SqlConnection);
```

Exception:
```
error CS0234: The type or namespace name 'SqlClient' does not exist in the namespace 'System.Data' (are you missing an assembly reference?)
```

**Comment by seesharper** [comment] 2017-06-20 17:43
Itellisense in VS Code looks okay?

**Comment by Sharpiro** [comment] 2017-06-20 17:48
no errors at all w/ Intellisense in VS Code.

Though now that i'm using project.json to deal w/ nuget packages and restore and the dotnet script nuget package, none of the examples in the previous post work under csi.exe anymore.

**Comment by seesharper** [comment] 2017-06-20 18:07
That is expected. CSI.EXE has no relation to project.json files and will only load what you specify using the #r directive. My guess is that this is related to the runtime assemblies we feed into the scripting engine. @filipw, correct me if I am wrong here, but VS Code (OmniSharp) only deals with the compile assemblies (reference assemblies) where as the scripting engine works with the actual runtime assemblies. The reference assemblies are empty assemblies just needed for compilation. 
As you might know already, project.json has been replaced with the new csproj format and it might be that we need a more robust way to resolve the runtime dependencies. 
The project exporter you see here is sort of legacy code as it only deals with project.json and project.lock.json files and there might be semantics in newer packages that is not taken care of here.
https://github.com/filipw/dotnet-script/blob/master/src/Dotnet.Script.Core/ScriptCompiler.cs#L75

**Comment by Sharpiro** [comment] 2017-06-22 15:48
I actually tried running virtually the same script under @seesharper 's csx tool and got the exact same error.

Script:
```
#! "netcoreapp1.1"
#r "nuget:NetStandard.Library,1.6.1"
#r "nuget:Microsoft.EntityFrameworkCore.SqlServer,1.1.2"
#r "nuget:System.Data.Common,4.1.0"
#r "nuget:System.Data.SqlClient,4.1.0"

using System.Linq;
using Microsoft.EntityFrameworkCore;

public class TempContext : DbContext
{
    public DbSet<Log> Logs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("empty");
}

public class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}
var context = new TempContext();
var logQuery = context.Logs.Where(l => l.Id == 1).ToList();
WriteLine(logQuery);
```

Exception:
```
    fail: csx.ScriptExecutor[0]
      System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The sy
stem cannot find the file specified.
      File name: 'System.Data.SqlClient, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the spec
ified file.
      File name: 'System.Data.SqlClient'
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerTransientExceptionDetector.ShouldRetryOn(Exception ex)
         at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
         at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
         at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at Submission#0.<<Initialize>>d__0.MoveNext() in C:\Users\me\Desktop\temp\csxgen\helloworld.csx:line 22
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
```

**Comment by seesharper** [comment] 2017-06-22 19:57
That is because it the code is essentially the same. The csx project is just a simple runner that I created to properly test DotNet.Script.NuGetMetadataResolver. Both projects use the [Microsoft.DotNet.ProjectModel](https://www.nuget.org/packages/Microsoft.DotNet.ProjectModel/1.0.0-rc3-1-003177) package that actually did not ever make it to release before Microsoft decided to ditch project.json and go with a new simplified csproj format. We use the same package in OmniSharp.Roslyn (Scripting) to provide the compile assemblies that is the basis for intellisense in VS Code. The script runner however needs the actual runtime assemblies and I suspect as mentioned before that there might be version negotiation implemented in tools that handle csproj filer (dotnet cli), that is not covered by this legacy preview package. Ideally we should move to csproj for scripting too since that is where it is all happening now. We might be good for at least a while in OmniSharp, but for runtime dependency resolving, we should move to csproj. One way to do this is to actually compile an netcore app begind the scenes and and read the  deps.json file to figure out the runtime dependencies needed for script execution. At least we have a failing scenario now :)

**Comment by filipw** [comment] 2017-06-22 20:45
The error is caused by a bug in this script runner, as it doesn't properly discover platform specific runtime dependencies. This should be fixed (I hope) by https://github.com/filipw/dotnet-script/pull/87

At least on my machine, when I now run your script I get:

```
An error occurred!
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 0.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Submission#0.<<Initialize>>d__0.MoveNext() in fixtures\sql\foo.csx:line 19
```

Which looks like something expected - because the connection string is malformated.

**Comment by Sharpiro** [comment] 2017-06-23 14:17
Just ran the same script under your ```bugfix/86``` branch, and I receive the same error about malformated connection string that you mentioned in the previous post.  But when given a valid connection string, I'm getting a new error.  I confirmed that script successfully returns data under dotnet core msbuild project. 

Error:
```
An error occurred!
System.DllNotFoundException: Unable to load DLL 'sni.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrent()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_ShapedQuery>d__3`1.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__15`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Submission#0.<<Initialize>>d__0.MoveNext() in c:\Users\me\Desktop\temp\gen\Main.csx:line 19

```

It looks like your fix allowed for the ```System.Data.SqlClient: 4.1.0``` to be loaded correctly, but now that assembly is trying to access a ```sni.dll``` unsuccessfully.

**Comment by seesharper** [comment] 2017-06-23 14:52
What can we do to redirect System.Data.SqlClient 4.1.0 to version 4.3.0 in the context of scripting. Creating a simple .Net Core console app does not require to explicitly references System.Data.SqlClient 4.1.0. Is this possibly a limitation of the Roslyn scripting engine?

**Comment by seesharper** [comment] 2017-06-28 20:31
@filipw @Sharpiro 
I have spent the last couple of days researching this and finally found a way to resolve runtime assemblies AND native libraries such as sni.dll. The code is still a rough around the edges and I have only tested this on Windows.  What is cool about this though is that it uses csproj rather than project.json.

I would be happy to create a PR to integrate this into this project as well.

The following code shows the basics of resolving the dependencies.

```
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text.RegularExpressions;
using Microsoft.Extensions.DependencyModel;
using Microsoft.Extensions.Logging;

namespace csx
{
    public interface IRuntimeDependencyResolver
    {
        IEnumerable<RuntimeDependency> GetRuntimeDependencies(string pathToProjectFile);
    }

    public class RuntimeDependencyResolver : IRuntimeDependencyResolver
    {
        private readonly ICommandRunner _commandRunner;

        private readonly ILogger _logger;

        // Note: Windows only, Mac and Linux needs something else?
        [DllImport("Kernel32.dll")]
        private static extern IntPtr LoadLibrary(string path);

        public RuntimeDependencyResolver(ICommandRunner commandRunner, ILoggerFactory loggerFactory)
        {
            _commandRunner = commandRunner;
            _logger = loggerFactory.CreateLogger<RuntimeDependencyResolver>();
        }

        private DependencyContext ReadDependencyContext(string pathToProjectFile)
        {
            Restore(pathToProjectFile);

            var pathToAssetsFiles = Path.Combine(Path.GetDirectoryName(pathToProjectFile), "obj", "project.assets.json");

            using (FileStream fs = new FileStream(pathToAssetsFiles, FileMode.Open, FileAccess.Read))
            {
                using (var contextReader = new DependencyContextJsonReader())
                {
                    return contextReader.Read(fs);
                }
            }
        }

        public IEnumerable<RuntimeDependency> GetRuntimeDependencies(string pathToProjectFile)
        {
            var pathToGlobalPackagesFolder = GetPathToGlobalPackagesFolder();
            var runtimeDepedencies = new HashSet<RuntimeDependency>();

            var context = ReadDependencyContext(pathToProjectFile);

            //Note: Scripting only releates to runtime libraries.
            var runtimeLibraries = context.RuntimeLibraries;

            foreach (var runtimeLibrary in runtimeLibraries)
            {
                ProcessNativeLibraries(runtimeLibrary, pathToGlobalPackagesFolder);
                ProcessRuntimeAssemblies(runtimeLibrary, pathToGlobalPackagesFolder, runtimeDepedencies);
            }

            return runtimeDepedencies;
        }

        private void ProcessRuntimeAssemblies(RuntimeLibrary runtimeLibrary, string pathToGlobalPackagesFolder,
            HashSet<RuntimeDependency> runtimeDepedencies)
        {
            
            foreach (var runtimeAssemblyGroup in runtimeLibrary.RuntimeAssemblyGroups.Where(rag => IsRelevantForCurrentRuntime(rag.Runtime)))
            {
                foreach (var assetPath in runtimeAssemblyGroup.AssetPaths)
                {
                    var path = Path.Combine(runtimeLibrary.Path, assetPath);
                    if (!path.EndsWith("_._"))
                    {
                        var fullPath = Path.Combine(pathToGlobalPackagesFolder, path);
                        _logger.LogInformation(fullPath);
                        runtimeDepedencies.Add(new RuntimeDependency(runtimeLibrary.Name, fullPath));
                    }
                }
            }
        }

        private void ProcessNativeLibraries(RuntimeLibrary runtimeLibrary, string pathToGlobalPackagesFolder)
        {            
            foreach (var nativeLibraryGroup in runtimeLibrary.NativeLibraryGroups.Where(nlg => IsRelevantForCurrentRuntime(nlg.Runtime)))
            {
                foreach (var assetPath in nativeLibraryGroup.AssetPaths)
                {
                    var fullPath = Path.Combine(pathToGlobalPackagesFolder, runtimeLibrary.Path,
                        assetPath);
                    _logger.LogInformation($"Loading native library from {fullPath}");
                    LoadLibrary(fullPath);
                }                
            }            
        }

        private void Restore(string pathToProjectFile)
        {
            _commandRunner.Execute("DotNet", $"restore {pathToProjectFile} -r win7-x64");
        }

        private string GetPathToGlobalPackagesFolder()
        {
            var result = _commandRunner.Execute("dotnet", "nuget locals global-packages -l");
            var match = Regex.Match(result, @"global-packages:\s*(.*)\r");
            return match.Groups[1].Captures[0].ToString();
        }

        public bool IsRelevantForCurrentRuntime(string runtime)
        {
            return string.IsNullOrWhiteSpace(runtime) || runtime == GetRuntimeIdentitifer();
        }

        private static string GetRuntimeIdentitifer()
        {
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) return "osx";
            if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX)) return "unix";

            return "win";
        }
    }

    public class RuntimeDependency
    {
        public string Name { get; }
        public string Path { get; }

        public RuntimeDependency(string name, string path)
        {
            Name = name;
            Path = path;
        }

        /// <inheritdoc />
        public override int GetHashCode()
        {
            return Name.GetHashCode() ^ Path.GetHashCode();
        }

        /// <inheritdoc />
        public override bool Equals(object obj)
        {
            var other = (RuntimeDependency)obj;
            return other.Name == Name && other.Path == Path;
        }
    }
}
```

**Comment by seesharper** [comment] 2017-09-13 19:00
The following script seems to work with the 0.13.0 release.
```
#! "netcoreapp1.1"
#r "nuget:Microsoft.EntityFrameworkCore.SqlServer, 1.1.2"


using Microsoft.EntityFrameworkCore;
using System.Linq;

public class MyContext : DbContext
{
    public DbSet<Log> Logs { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) => optionsBuilder.UseSqlServer("empty");
}

public class Log
{
    public int Id { get; set; }
    public string Value { get; set; }
}

var context = new MyContext();
try
{
    var logsQueryable = context.Logs.Take(1);
    Console.WriteLine(logsQueryable);
}
catch (Exception ex)
{
    Console.WriteLine("An error occurred!");
    Console.WriteLine(ex);
}
```

**Closed by seesharper** 2017-09-13 19:00 UTC
